---
# Linguagem e versão do projeto
language: node_js

# Quais branches acionarão os jobs
branches:
  only:
    - master

# Integração com o Docker Registry
integrations:
  hub:
    - integrationName: docker-registry
      type: dockerRegistryLogin

# Variáveis
env:
  global:
    - DOCKER_REPO="qconsp-site"
    - DOCKER_ACC=lowbit
    - SHIP_IMG_RES="docker_image_site"

build:
  ci:
    # Construindo imagem docker
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    # Armazenando imagem docker
    - docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER
  on_success:
    # Salvando informações sobre esta imagem para usar adiante no Workflow
    - shipctl put_resource_state $SHIP_IMG_RES versionName $BRANCH.$BUILD_NUMBER

resources:
  # Imagem Docker gerada
  - name: docker_image_site
    type: image
    integration: docker-registry
    versionTemplate:
      sourceName: "lowbit/qconsp-site"
      isPull: false
      versionName: latest

jobs:
  # Gravando a versão da imagem no objeto (recurso) acima
  - name: qconsp-dev-site_runCI
    type: runCI
    steps:
      - OUT: docker_image_site
